config/routes.rb
Rails.application.routes.draw do
  
  mount ActionCable.server => "/cable"
  
  resources :friendships, only: [:create, :update, :destroy]
  resources :categories, only: [:show, :index]
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :users, only: [:index, :show] do
    collection do   
      get 'search'
    end
  end

  get 'followers', to: 'users#followers'
  get 'following', to: 'users#following'
  get 'drafts', to: 'articles#drafts'
  
  resources :articles do
    resources :comments, only: [:create, :update, :destroy, :edit]
    member do
      get 'upvote'
      get 'downvote'
    end
  end
  
  resources :notifications, only: [:index, :destroy]
  
  resources :conversations, only: [:index, :new] do
    collection do   
      get 'list'
    end
  end

  resources :conversations, only: [:create] do
    resources :messages, only: [:create]
  end
  
  get 'refresh', to: 'pages#refresh'
  get 'follow_recommended', to: 'pages#follow_recommended'
  get 'about', to: 'pages#about'

  root 'pages#home'

  match "*path", to: "application#catch_404", via: :all

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/article.rb
class Article < ApplicationRecord
  enum status: { draft: 1, published: 0 }
  extend FriendlyId
  friendly_id :title, use: :slugged
  is_impressionable :counter_cache => true, :unique => false
  acts_as_votable
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :users, through: :comments
  has_many :impressions, as: :impressionable
  has_many :article_categories
  has_many :categories, through: :article_categories

  validates :title, presence: true, length: { minimum: 10, maximum: 100 }
  validates :summary, presence: true, length: { minimum: 10, maximum: 180 }
  validates :description, presence: true, length: { minimum: 10 }
  
  def age_group
    months_between = Date.today.month - self.created_at.month
    if months_between > 12
        age = "more than 1 year ago"
    elsif months_between  <= 12
        age = "less than 1 year ago"
    elsif months_between  <= 3
        age = "less than 3 months ago"
    elsif months_between <= 1
        age = "less than 1 month ago"
    end
  end
  
  scope :order_by_title_asc, -> { order(title: :asc) }
  scope :order_by_title_desc, -> { order(title: :desc) }
  scope :order_by_created_at_desc, -> { order(created_at: :desc) }
  scope :order_by_impressions_count_desc, -> { order(impressions_count: :desc) }
  scope :order_by_cached_votes_up_desc, -> { order(cached_votes_up: :desc) }

              
  def self.order_by
	[
	    ['Sort By', ''],
		['Newest', 'created_at desc'],
		['Title: A to Z', 'title asc'],
		['Title: Z to A', 'title desc'],
		['Highest View Count', 'impressions_count desc'],
		['Highest Rated', 'cached_votes_up desc'],
	]
  end
  
  def popular_score
    return ((self.impressions_count * 0.6) + (self.cached_votes_up * 0.4))
  end
  
  def self.sorted_by_popular_score
    Article.all.sort_by(&:popular_score).reverse
  end

  def self.article_impression_count
     self.joins(:categories).group('categories.name').sum(:impressions_count)
  end
  

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, except:[:index, :show]
  before_action :set_article, only: [:show, :edit, :update, :destroy, :upvote, :downvote]
  include ArticlesHelper
  
  def index
    @q = Article.published.ransack(params[:q])
    @q.sorts = 'created_at desc' if @q.sorts.empty?
    @articles = @q.result(distinct: true).includes(:categories, :users).paginate(page: params[:page], per_page: 15)
    @categories = Category.with_articles.order('name ASC').all

    if params[:s] != nil
      if params[:q][:s] == 'title asc'
        @articles = @articles.order_by_title_asc
      elsif params[:q][:s] == 'title desc'
        @articles = @articles.order_by_title_desc
      elsif params[:q][:s] == 'created_at desc'
        @articles = @articles.order_by_created_at_desc
      elsif params[:q][:s] == 'impressions_count desc'
        @articles = @articles.order_by_impressions_count_desc
      elsif params[:q][:s] == 'cached_votes_up desc'
        @articles = @articles.order_by_cached_votes_up_desc
      end
    end
  end
  
  def show
    if @article.status == "draft" && @article.user != current_user
      redirect_to root_path
    else
      @article_categories = @article.categories
      @comments = @article.comments
      @new_comment = @article.comments.new
      impressionist(@article)
    end
  end
  
  def new
    @article = Article.new(:status => "published")
  end

  def create
    @article = current_user.articles.new(article_params)
    if @article.save
      flash[:success] = 'Your article was created successfully'
      redirect_to @article
    else
      render action: :new
    end
  end

  def edit
    if @article.user != current_user then 
      redirect_to root_path 
      flash[:error] = 'You are not authorized to edit this article'
    end
  end

  def update
    if @article.update(article_params)
      flash[:success] = 'Your article was edited successfully'
      redirect_to @article
    else
      render action: :edit
    end
  end

  def destroy
    @article.destroy
    flash[:success] = 'Your article was deleted successfully'
    redirect_to articles_path
  end
  
  def upvote
    @article.upvote_by current_user
    respond_to do |format|
      format.html { redirect_to @article }
      format.js
      end
  end
   
  def downvote
    @article.downvote_by current_user
    respond_to do |format|
      format.html { redirect_to @article }
      format.js
      end
  end
  
  def drafts
    @articles = current_user.articles.draft.paginate(page: params[:page], per_page: 10).order("updated_at DESC")
  end

  private

    def set_article
      @article = Article.friendly.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:title, :summary, :description, :user_id, :status, category_ids: [])
    end

end

app/helpers/articles_helper.rb
module ArticlesHelper
    
  def display_likes(article)
    votes = article.votes_for.up.by_type(User)
    count_likers(votes)
  end
  
  private

  def count_likers(votes)
    vote_count = votes.size
    vote_count.to_s +  'likes'
  end
  
  def like_plural(votes)
    return 'like this' if votes.count > 1
    'likes this'
  end
  
end

app/views/articles/_article.html.erb
<div class = "row" id="article_<%= article.id %>" >  
    <div id = "vote-viewcount-block" class="col-md-2 col-sm-2 col-xs-12">
      <h3><%= article.get_upvotes.size %></h3><small>votes</small><br>
      <% if article.impressions_count? == false %>
      <h3>0</h3><small>views</small><br>
      <% else %>
      <h3><%= article.impressions_count %></h3><small>views</small><br>
      <% end %>
    </div> 
    <div id = "content-block" class="col-md-7 col-sm-7 col-xs-12">
      <div id = "article-content">
        <h3><%= link_to article.title, article_path(article) %></h3>
        <%= article.summary %>
      </div>
      <div id = "category-block">
        <% article.categories.each do |category| %>
        <%= link_to "#{category.name}", category_path(category), class: "btn btn-xs btn-info" %>
        <% end %>
      </div>
    </div>
    <div id="article-details" class="col-md-3 col-sm-3 col-xs-12">
      <div id = "user-console">
        <% if current_user == article.user %>
          <%= link_to edit_article_path(article), class: "btn btn-xs btn-default" do %>
            <i class="glyphicon glyphicon-pencil"></i> 
          <% end %>
          <%= link_to article_path(article), method: :delete, data: { confirm: "Are you sure you want to delete the article?"}, class: "btn btn-xs btn-default icon-delete" do %>
            <i class="glyphicon glyphicon-trash"></i> 
          <% end %>
        <% end %>
      </div>
      <div id = "details-panel">
        <%= gravatar_for(article.user, size:40) %>
        <p><b><%= article.user.name %></b></p><br>
        <small>Created: <%= article.created_at.strftime("%d-%m-%Y") %></small><br>
        <small>Updated: <%= time_ago_in_words(article.updated_at) %> ago</small>
      </div>
    </div>
</div>
<hr>

app/views/articles/_browse_form.html.erb
<div class ="jumbotron" id="browse-form">
  <%= search_form_for q, url: articles_path, method: :get, id: "form" do |f| %>
    <div class="form-group">
      <div class = "row">
        <div class="col-md-12 col-sm-12 col-xs-12">
          <%= f.search_field :title_cont, placeholder: "Find Articles", class: "form-control" %>
        </div>
      </div>
    </div>
    <div class="advanced-search hidden">
        <a class="close-advanced-search fi-x"></a>
        <div class="form-group">
          <div class ="row">
            <div class="col-md-6 col-sm-6 col-xs-12">
              <%= f.search_field :user_name_cont, class: "form-control", placeholder: "Author" %>
            </div>
            <div class="col-md-6 col-sm-6 col-xs-12">

                  <%= f.collection_select :categories_name_in, Category.all, "name", "name", 
                                    { :include_hidden => false },
                                    { :multiple => true, 
                                      :id => "cat-dropdown-menu" } %>

            </div>
          </div>
        </div>
    </div>
    <div class="form-group">
      <%= f.hidden_field :s, value: q.s || params[:q][:s] %>
      <%= f.submit class: 'btn btn-md btn-default' %>
      <a class="show-advanced-search"> Advanced Search</a> |
      <%= link_to "Clear Search", articles_path %>
    </div>
    <% end %>

</div>

<%= select_tag "", options_for_select(Article.order_by, q.s), class: "sortBy" %>

app/views/articles/_browse_sidebar.html.erb
<div id="browse-title">
  <% if params[:q].present? == true %>
    <div style="background-color:#e0e3e4; width: 300px; height: 194px; margin:20px 0px; padding-top:10px;">
      <img class='image' style="width:300px" src="https://storage.googleapis.com/f1-project/website_images/search_results.png"> 
    </div>
  <% else %>
    <div style="background-color:#e0e3e4; width: 300px; height: 194px; margin:20px 0px; padding-top:10px;">
      <img class='image' style="width:300px" src="https://storage.googleapis.com/f1-project/website_images/browse_articles.png">
    </div>
  <% end %>
  <% if params[:q].present? == true %>
    <p><b><%= articles.count %></b> articles were found based on your criteria </p>
  <% end %>
</div>  

<div id="browse-tags">
  <h4><b>Tags:</b></h4>
  
   <% if q.title_cont.present? == true %>
    <button type="button" class = "btn btn-tag">
        <%= q.title_cont.truncate(30, omission: '... ') %> 
    </button>
   <% end %>
    
   <% if q.categories_name_in.present? == true %>
      <% q.categories_name_in.each do |name|  %>
        <button type="button"class = "btn btn-tag">
            <%= name %> 
        </button>
      <% end %>
   <% end %>
     
    <% if q.user_name_cont.present? == true %>
      <button type="button" class = "btn btn-tag">
        <%= params[:q][:user_name_cont] %>
      </button>
   <% end %>
</div>
    
<div id="browse-category">
  <h4><b>Category:</b></h4>
  <% if params[:q].present? == true %>
    <% categories.each do |category| %>
      <% c = category.articles.ransack(params[:q]).result(distinct: true).count %>
      <% if c > 0 %>
        <%= link_to articles_path('q[title_cont]' => params[:q][:title_cont],
                                         'q[categories_name_cont]' => category.name,
                                         'q[user_name_cont]' => params[:q][:user_name_cont]) do %>
          <h4><%= category.name %> (<%= c %>)</h4>
        <% end %>
      <% end %>
    <% end %>
  <% else %>
    <% categories.each do |category| %>
    <div class="padding-top-10">
      <h4><%= link_to "#{category.name} (#{category.articles.count})", category_path(category) %></h4>
    </div>
    <% end %>
  <% end %>
</div>

app/views/articles/_form.html.erb
<div id="article-form">
  <%= form_for @article, id: "new_article" do |f| %>
  
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: "form-control", autofocus: true %>
    </div>
    
    <div class="form-group">
      <%= f.label :summary %>
      <%= f.text_field :summary, class: "form-control" %>
    </div>
    
    <div class="form-group">
      <%= f.cktext_area :description, rows: 20, class: "form-control", ckeditor: { uiColor: '#cfcfcf'} %>
    </div>
    
    <div class="form-group">                                                                       
      <%= f.label :category %>
      <%= f.collection_select :category_ids, Category.all, :id, :name, {}, {:multiple => true, class: "form-control"} %>
    </div>
    
    <div class="form-group">
      <%= f.label "Do you want to publish?" %>
      <%= f.radio_button :status, 'draft', class: "margin-left-20" %>
      <%= f.label :status, 'Draft' %>
      <%= f.radio_button :status, 'published' %>
      <%= f.label :status, 'Publish' %>
    </div>
    
    <div class="form-group padding-top-10">
        <%= f.submit "Post your article", class: 'btn btn-primary btn-md' %>
    </div>

  <% end %>
</div>

app/views/articles/_show_sidebar.html.erb
<h4><%= pluralize(article.impressions_count, 'view') %></h4>

<%= render 'vote', article: article %>  

<% if user_signed_in? == false %>
  <h4 class ="click-caption"> Sign in to vote!</h4>
<% else %>
  <h4 class ="click-caption">Click to like!</h4>
  <% if current_user.voted_up_on? article %>
    <%= link_to '', downvote_article_path(article.id), remote: true,
                          id: "vote_#{article.id}",
                          class: 'glyphicon glyphicon-heart' %>
  <% else %>
    <%= link_to '', upvote_article_path(article.id), remote: true,
                          id: "vote_#{article.id}",
                          class: 'glyphicon glyphicon-heart-empty' %>
  <% end %>
<% end %>

app/views/articles/_vote.html.erb
<div class="vote">
  <h4><%= pluralize(article.get_upvotes.size, 'like') %></h4>
</div>

app/views/articles/downvote.js.erb
$("#vote_<%= @article.id %>").removeClass('glyphicon-heart').addClass('glyphicon-heart-empty');
$("#vote_<%= @article.id %>").attr("href", '/articles/<%= @article.id %>/upvote');
$(".vote").html("<%= j (render partial: 'articles/vote', locals: { article: @article } ) %>");

app/views/articles/drafts.html.erb
<div class = "container">
  <h1 align="center">My Drafts</h1>
  <div class = "row">
    <div class = "col-md-9">
     <% @articles.each do |article| %>
       <%= render 'article', article: article %>
     <% end %>
     <%= will_paginate %>
    </div>
    <div class = "col-md-3"></div>
  </div>
</div>

app/views/articles/edit.html.erb
<div class = "container">
  <div class = "row">
    <h1 style="padding-left: 20px">Edit Post</h1>
    <%= render 'form' %>
  </div>
</div>

app/views/articles/index.html.erb
<div class = "container">
  <div class = "row">
    <div class = "col-md-4 col-sm-12 col-xs-12" id="browse-sidebar">
      <%= render 'browse_sidebar', articles: @articles, categories: @categories, q: @q %>
    </div>
    <div class = "col-md-8 col-sm-12 col-xs-12">
      <%= render 'browse_form', q: @q %>
      <%= render @articles %>
      <%= will_paginate @articles, :inner_window => 1, :outer_window  => 1, :previous_label => '&larr;'.html_safe, :next_label => '&rarr;'.html_safe %>
    </div>
  </div>
</div>

app/views/articles/new.html.erb
<div class = "container">
  <div class = "row">
     <h1 style="padding-left: 20px">Create a new article</h1>
      <%= render 'form' %>
  </div>
</div>

app/views/articles/show.html.erb
<div class = "container-fluid" id="article">
  
  <div id = "article-show-header">
    <div class = "article-header-text">
      <h1><%= @article.title %></h1>
      <span><%= @article.created_at.strftime("%d-%m-%Y") %></span>
      <span>Last updated: <%= @article.updated_at.strftime("%d-%m-%Y") %></span>
      <span>By: <%= @article.user.name %></span>
      <span>
        <% if current_user == @article.user %>
          <%= link_to 'Edit', edit_article_path(@article) %> |
          <%= link_to 'Delete', article_path(@article), method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
      </span>
    </div>
    <div>
      <% @article_categories.each do |category| %>
          <%= link_to "#{category.name}", category_path(category), class: "btn btn-xs btn-article-show" %>
      <% end %>
    </div>
  </div>

  <div class='row' style="width:60%; margin:auto">
    <hr>
    <div id= "article-description">
      <%= raw(@article.description) %>
    </div>
    <div id = "read-more">
      <button class="hidden btn btn-cat-loadmore">Read More</button>
    </div>
     <hr>
  </div>

  <div class = "row">
    <div id="small-article-sidebar">
        <%= render 'show_sidebar', article: @article %>
    </div>
  </div>

  <div class = "row" id="article-comments">
    <div class = "col-md-1 col-sm-1 col-xs-1"></div>
    <div class = "col-md-10 col-sm-10 col-xs-10">
      <% if user_signed_in? == false %>
        <h4 class ="click-caption">You must Sign in/Create an account to post a comment</h4>
      <% else %>
        <div id="comment-form">
          <%= render 'comments/comment_form' %>
        </div>
      <% end %>
      <div id = "comments-count">
        <p>This article has 0 comments</p>
      </div>
      <div id = "comment-list" >
        <%= render partial: @article.reload.comments %>
      </div>
    <div class = "col-md-1 col-sm-1 col-xs-1"></div>
    </div>
  </div>

</div>

app/views/articles/toggle_vote.js.erb
$("#article-sidebar").html(“<%= j (render 'show_sidebar', article: @article) %>”);

app/views/articles/upvote.js.erb
$("#vote_<%= @article.id %>").removeClass('glyphicon-heart-empty').addClass('glyphicon-heart');
$("#vote_<%= @article.id %>").attr("href", '/articles/<%= @article.id %>/downvote');
$(".vote").html("<%= j (render partial: 'articles/vote', locals: { article: @article } ) %>");