config/routes.rb
Rails.application.routes.draw do
  
  mount ActionCable.server => "/cable"
  
  resources :friendships, only: [:create, :update, :destroy]
  resources :categories, only: [:show, :index]
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :users, only: [:index, :show] do
    collection do   
      get 'search'
    end
  end

  get 'followers', to: 'users#followers'
  get 'following', to: 'users#following'
  get 'drafts', to: 'articles#drafts'
  
  resources :articles do
    resources :comments, only: [:create, :update, :destroy, :edit]
    member do
      get 'upvote'
      get 'downvote'
    end
  end
  
  resources :notifications, only: [:index, :destroy]
  
  resources :conversations, only: [:index, :new] do
    collection do   
      get 'list'
    end
  end

  resources :conversations, only: [:create] do
    resources :messages, only: [:create]
  end
  
  get 'refresh', to: 'pages#refresh'
  get 'follow_recommended', to: 'pages#follow_recommended'
  get 'about', to: 'pages#about'

  root 'pages#home'

  match "*path", to: "application#catch_404", via: :all

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/conversation.rb
class Conversation < ApplicationRecord
    
belongs_to :author, class_name: 'User'
belongs_to :receiver, class_name: 'User'
validates :author, uniqueness: {scope: :receiver}
validate :author_cannot_be_receiver

has_many :personal_messages, -> { order(created_at: :asc) }, dependent: :destroy
has_many :all_unread_messages, -> { where(read_at: nil) }, class_name: "PersonalMessage", foreign_key: "conversation_id"

#scopes
default_scope { order(updated_at: :desc) }

scope :participating, -> (user) do
  where("(conversations.author_id = ? OR conversations.receiver_id = ?)", user.id, user.id)
end

scope :by_unread, -> (user) do
  where("(conversations.author_id = ? OR conversations.receiver_id = ?)", user.id, user.id)
  .joins('RIGHT JOIN "personal_messages" ON "personal_messages"."conversation_id" = "conversations"."id"')
  .where.not(personal_messages: {user_id: user.id})
  .where(personal_messages: { read_at: nil})
  .reorder('personal_messages.read_at asc').uniq
end

def last_string
  personal_messages.last.body rescue nil
end

def with(current_user) #returns the other participant of a conversation
  author == current_user ? receiver : author
end

def participates?(user)
  author == user || receiver == user
end

def unread_messages_count current_user
  _w = with(current_user)
  all_unread_messages.where(user_id: _w.id).count
end

def read! current_user
  unread_messages(current_user).update(read_at: Time.now)
end

def unread_messages current_user
  _w = with(current_user)
  personal_messages.where(read_at: nil, user_id: _w.id)
end

scope :between, -> (author_id, receiver_id) do
  where(author_id: author_id, receiver_id: receiver_id).or(where(author_id: receiver_id, receiver_id: author_id)).limit(1)
end

def self.get(author_id, receiver_id)
  conversation = between(author_id, receiver_id).first
  return conversation if conversation.present?
  create(author_id: author_id, receiver_id: receiver_id)
end

def self.options_for_filter
	[
		['Unread', 'unread'],
		['All', 'read'],

	]
end

private
  def author_cannot_be_receiver
    if author == receiver
       errors[:base] = "Cannot send message to self"
    end
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :authenticate_user!
    def index
      @conversation_list = Conversation.participating(current_user)
    end

    def create
      if params["conversation_id"]
        @conversation = Conversation.find(params["conversation_id"])
      elsif 
        @conversation = Conversation.get(current_user.id, params["user_id"])
      end
      @conversation.read!(current_user) if @conversation
      respond_to do |format|
        format.html { redirect_to conversations_path }
        format.js
      end
    end

    def list
      if params[:type] == 'unread'
        @conversation_list = Conversation.by_unread(current_user)
      else
        @conversation_list = Conversation.participating(current_user)
      end
        
      respond_to do |format|
        format.html { redirect_to conversations_path }
        format.js
      end
    end
     
    def new
      respond_to do |format|
        format.html { redirect_to conversations_path }
        format.js
      end
    end

end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/_conversation.html.erb
<ul class="list-unstyled" data-conversation-id="<%= conversation.id %>">
	<%= render 'conversations/conversation_content', personal_messages: conversation.personal_messages, user: user %>
</ul>

app/views/conversations/_conversation_content.html.erb
<% personal_messages.each do |personal_message| %>
  <%= render personal_message, user: user %>
<% end %>

app/views/conversations/_member_convo.html.erb
<%= link_to  conversations_path(user_id: user), remote: true, method: :post do %>
  <span class="chat-img pull-left">
    <%= gravatar_for(user, size: 20) %>
  </span>
  <div class="chat-body clearfix">
    <div class="header_sec">
       <strong class="primary-font"><%= user.name %></strong>
    </div>
    <div class="contact_sec">
       <strong class="primary-font"><%= conversation.last_string %></strong> 
       <% message_count = conversation.unread_messages_count(logged_user) %>
       <span class="badge pull-right <%= 'hidden' if message_count < 1 %>">
       <%= message_count %></span>
    </div>
  </div>
<% end %>

app/views/conversations/_member_list.html.erb
<ul class="list-unstyled">
  <% @conversation_list.each do |conversation| %>
    <% user = conversation.with current_user %>
    <li class="left clearfix" data-conversation-member= <%= conversation.id %> >
      <%= render "conversations/member_convo" , user: user, conversation: conversation, logged_user: current_user %>
    </li>
  <% end %>
</ul>

app/views/conversations/_new.html.erb
<div class="message_section">
    <div class="row">
        <div class="new_message_head">
            <div class="pull-left">
                <button class="NewMsgS">New Message</button>
            </div>
            <!--new_message_head-->
            <div class="message_write">
                <%= form_tag conversations_path, remote: true do  %>
                    <%= select_tag :user_id, [], class: "form-control users_select" %>
                    <br>
                    <%= hidden_field_tag "new_message", true %>
                    <textarea name="body" class="form-control" placeholder="Type a message..."></textarea>
                    <div class="clearfix"></div>
                    <div class="chat_bottom">
                        <input type="submit" class=" btn btn-success" value="Send">
                        <%= link_to conversations_path, class: "btn btn-default" do %>
                            Cancel
                            <% end %>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
    <!--message_section-->
</div>

app/views/conversations/_send_form.html.erb
<form action = "conversations/index" class="new_message">
	<input name="conversation_id" type="hidden" value="<%= conversation.id %>">
	<input name="user_id" type="hidden" value="<%= user.id %>">
	<textarea name="body" class="form-control"></textarea><br>
	<input type="submit" class="pull-right btn btn-success" value="Send">
</form>

app/views/conversations/create.js.erb
<%if params["new_message"] %>
	values = {}
	values = [{
		"name": "conversation_id",
		"value": "<%= @conversation.id %>",
	},
	{
		"name": "user_id",
		"value": '<%= current_user.id %>'
	},
	{
		'name' : 'body',
		'value': '<%= params["body"] %>'

	}];
	App.conversation.speak(values);
<% end %>
var chat_area = $('.chat_area');
var header_con = $('.HeaderMsg').addClass("new_message_head");
header_con.html('<div class="pull-left"><button>Conversation with <%= @conversation.with(current_user).name %></button></div>')
chat_area.html("<%= j(render 'conversations/conversation', conversation: @conversation, user: current_user) %>");

var conversation = chat_area.find("[data-conversation-id='" + "<%= @conversation.id %>" + "']");
conversation.find('.panel-default').show();

var message_div = $('.message_wroteD').addClass('message_write');
$('.message_wroteD').html("<%= j(render 'conversations/send_form', conversation: @conversation, user: current_user) %>")
if (chat_area.length){
	var height = chat_area[0].scrollHeight;
	chat_area.scrollTop(height);
}
// FOR BADAGE
var member = $('<%= "[data-conversation-member=#{@conversation.id}]" %>');
member.find('.badge').addClass('hidden').text('');

app/views/conversations/index.html.erb
<style type="text/css">
  #ComposeFrm .topEl {
    text-decoration: none;
    border-radius: 5px;
    padding: 7px 0 10px 0px;
    font-size: 12px;
    border: none;
    color: #fff;
    min-width: 90px;
    text-align: center;
    display: inline-block;
    vertical-align: top;
  }
  #ComposeFrm .topEl.topElSelect{
    float: right;
    width: 100px;
  }
</style>

<div class="main_section">
  <div class="container">
    <div class="chat_container">
      <div class="col-sm-4 col-xs-4 chat_sidebar">
        <div class="row">
          <div id="custom-search-input">
            <div  class="input-group col-md-12 col-sm-12 col-xs-12">
              <form action="#unread" class="form-inline" id="ComposeFrm">
                <div class="form-group topEl">
                  <%= link_to new_conversation_path, class: "btn btn-default", remote: true do %>
                    Compose
                  <% end %>
                </div>
                <div class="form-group topEl topElSelect">
                  <%= select_tag "", options_for_select(Conversation.options_for_filter, 'unread'), class: "form-control topESelect", data: {url: list_conversations_path}%>
                </div>
              </form>
            </div>
            <div class="input-group col-md-12 col-sm-12 col-xs-12">
              
            </div>
          </div>
          <div class="dropdown all_conversation">
             <button class="dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
             All Conversations
          </div>
          <div class="member_list" id="member_list">
            <%= render 'conversations/member_list' %>
          </div>
        </div>
      </div>
      <!--chat_sidebar-->

      <div class="col-sm-8 col-xs-8 message_section">
        <div class="row">
          <div class="HeaderMsg"></div><!--new_message_head-->
          <div class="chat_area">
              <p class="text-center"> Please select message thread to read it here</p>
          </div><!--chat_area-->
          <div class="message_wroteD"></div>
        </div>
      </div> <!--message_section-->
    </div>
  </div>
</div>

app/views/conversations/list.js.erb
var member_list = $('#member_list');
member_list.html("<%= j(render 'conversations/member_list') %>");

app/views/conversations/new.js.erb
var message_div = $('.message_wroteD').removeClass('message_write').html('');
var header_con = $('.HeaderMsg').removeClass("new_message_head").html('');
var chat_area = $('.chat_area');
chat_area.html("<%= j(render 'conversations/new',user: current_user) %>");
$(document).trigger('init:users_select');