config/routes.rb
Rails.application.routes.draw do
  
  mount ActionCable.server => "/cable"
  
  resources :friendships, only: [:create, :update, :destroy]
  resources :categories, only: [:show, :index]
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :users, only: [:index, :show] do
    collection do   
      get 'search'
    end
  end

  get 'followers', to: 'users#followers'
  get 'following', to: 'users#following'
  get 'drafts', to: 'articles#drafts'
  
  resources :articles do
    resources :comments, only: [:create, :update, :destroy, :edit]
    member do
      get 'upvote'
      get 'downvote'
    end
  end
  
  resources :notifications, only: [:index, :destroy]
  
  resources :conversations, only: [:index, :new] do
    collection do   
      get 'list'
    end
  end

  resources :conversations, only: [:create] do
    resources :messages, only: [:create]
  end
  
  get 'refresh', to: 'pages#refresh'
  get 'follow_recommended', to: 'pages#follow_recommended'
  get 'about', to: 'pages#about'

  root 'pages#home'

  match "*path", to: "application#catch_404", via: :all

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :name, presence: true, length: {maximum: 20}
  validates :name, uniqueness: { case_sensitive: false }, if: -> { self.name.present? }
  validates_format_of :name, with: /^[a-zA-Z0-9_\.]*$/, :multiline => true
  validate :validate_name
  acts_as_voter       
  has_many :articles, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :notifications, foreign_key: :recipient_id
  has_many :friendships
  has_many :received_friendships, class_name: "Friendship", foreign_key: "friend_id"
  
  # active friend: current user sends a request which has been accepted by other party
  has_many :active_friends, -> { where(friendships: { accepted: true}) }, through: :friendships, source: :friend
  
  # received friend: other user sends a request which has been accepted by current user
  has_many :received_friends, -> { where(friendships: { accepted: true}) }, through: :received_friendships, source: :user
  
  # pending friend: current user sends a request which has not been accepted by other party
  has_many :pending_friends, -> { where(friendships: { accepted: false}) }, through: :friendships, source: :friend
  
  # requested friendship: other user sends a request which has not been accepted by current user
  has_many :requested_friendships, -> { where(friendships: { accepted: false}) }, through: :received_friendships, source: :user
  
  has_many :authored_conversations, class_name: 'Conversation', foreign_key: 'author_id'
  has_many :received_conversations, class_name: 'Conversation', foreign_key: 'received_id'
  has_many :personal_messages, dependent: :destroy
  
  scope :all_except, ->(user) { where.not(id: user) }

  def self.top_10_most_authored 
    self.joins(:articles)
        .group("users.id")
        .select("users.id, email, name, count(DISTINCT articles.id) AS articles_count")
        .order("count(DISTINCT articles.id) DESC")
        .limit(10)
  end
  
  def self.popular_users
    self.joins("RIGHT JOIN friendships ON friendships.friend_id = users.id AND friendships.accepted = 't'")
        .group("users.id")
        .select("users.id, count(DISTINCT friendships.id) AS followers_count")
        .order("count(DISTINCT friendships.id) DESC")
  end
  
  def self.active_users
    User.where('last_sign_in_at >= ?', 1.month.ago)
  end
  
  def self.sorted(current_user)
    self.where.not(id: current_user.self_initiated_friends)
        .where.not(id: current_user)
        .popular_users
        .top_10_most_authored
        .active_users
  end
  

  def login=(login)
    @login = login
  end

  def login
    @login || self.name || self.email
  end
    
  def friends
    active_friends | received_friends
  end

  def pending
    pending_friends | requested_friendships
  end
  
  def self_initiated_friends
    active_friends | pending_friends
  end
  
  def follows?(new_friend)
    friendships.map(&:friend).include?(new_friend)
  end
  
  def self.search(search)
      where('name LIKE ?', "%#{search}%")
  end

  def feed
    following_ids = "SELECT friend_id FROM friendships
                     WHERE (user_id = :user_id AND accepted = 't')"
    Article.published.where("user_id IN (#{following_ids})
                     OR user_id = :user_id", user_id: id)
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_hash).where(["lower(name) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    elsif conditions.has_key?(:name) || conditions.has_key?(:email)
      where(conditions.to_h).first
    end
  end

  def validate_name
    if User.where(email: name).exists?
      errors.add(:name, :invalid)
    end
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @search = User.ransack(params[:user])
    @users = @search.result(distinct: true).paginate(page: params[:page], per_page: 10)
  end
  
  def followers
    @followers = current_user.received_friends.all
    @requested_friendships = current_user.requested_friendships.all
  end
  
  def following
    @following = current_user.active_friends.all
  end

  def show
    @user = User.find(params[:id])
    @user_articles = @user.articles.all
  end
  
  def search
    param = params[:q][:term] rescue ""
    results = User.all_except(current_user).where("users.email iLike ? ", "%#{param}%")
    respond_to do |format|
      format.html { redirect_to users_path }
      format.json { render json:{:users => results } }
    end
  end


end

app/helpers/users_helper.rb
module UsersHelper
  # Returns the Gravatar for the given user.
  def gravatar_for(user, size: 60)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end

end

app/views/users/_followers_list.html.erb
<h3 class = "padding-bottom-40">You have <%= pluralize(followers.count, 'follower') %></h3>
<div class = "followers-list">
  <% followers.each do |follower| %>
    <%= render 'users/user', user: follower %>
  <% end %>
</div>

app/views/users/_following.html.erb
<div class = "container-fluid">
  <h3 class = "padding-bottom-40">Following <%= @following.count %> people</h3>
  <% @following.each do |following| %>
    <div class="row alternate-row">
      <div class = "col-md-1">
        <%= gravatar_for(following) %>
      </div>
      <div class = "col-md-9">
        <b><%= link_to following.name, user_path(following) %></b><br>
        <p><%= pluralize(following.articles.count, "article") if following.articles %></p>
      </div>
      <div class = "col-md-2">
        <%= link_to "Unfollow", user_path(following), 
        method: :delete, data: { confirm: "Are you sure?" }, class:"btn btn-outline-primary" %>
      </div>
    </div>
  <% end %>
</div>

app/views/users/_pending_list.html.erb
<h3 class = "padding-bottom-40">You have <%= pluralize(requested_friendships.count, "pending friend request") %></h3>
<div class = "pending-requests-list" %>
  <% requested_friendships.each do |requested_friendship| %> 
    <%= render 'users/requested_friendship', requested_friendship: requested_friendship %>
  <% end %>
</div>

app/views/users/_requested_friendship.html.erb
<div class="row alternate-row" id="requested_friendship_<%= requested_friendship.id %>">
  <div class = "col-md-1 col-xs-2">
    <%= gravatar_for(requested_friendship, size: 45) %>
  </div>
  <div class = "col-md-8 col-xs-3">
    <b><%= link_to requested_friendship.name, user_path(requested_friendship) %></b>
  </div>
  <div class = "col-md-3 col-xs-7">
    <%= link_to "Accept",  friendship_path(requested_friendship.friendships.find_by_friend_id(current_user)), method: "put", remote: true, class: "btn btn-sm btn-info" %>
    <%= link_to "Decline", friendship_path(requested_friendship.friendships.find_by_friend_id(current_user)), method: :delete, remote: true, class: "btn btn-sm btn-default" %>
  </div>
</div>

app/views/users/_status_buttons.html.erb
<% if user == current_user %>
   <div></div>
<% elsif current_user.pending_friends.include?(user) == true %> 
  <button type="button" class="btn btn-pending">Pending</button>
<% elsif current_user.active_friends.include?(user) == true %>
  <%= link_to friendship_path(current_user.friendships.find_by_friend_id(user.id)), :method => :delete,
  data: { confirm: "Are you sure?" }, class:"btn btn-unfollow", remote: true do %>
    <i class="fa fa-minus" aria-hidden="true"></i>
  <% end %>
<% elsif current_user.follows?(user) == false %>
  <%= link_to friendships_path(friend_id: user.id), method: :post, class: "btn btn-follow", remote: true do %>
    <i class="fa fa-plus" aria-hidden="true"></i>
  <% end %>
<% end %>

app/views/users/_status_buttons_words.html.erb
<% if user == current_user %>
   <div></div>
<% elsif current_user.pending_friends.include?(user) == true %> 
  <button type="button" class="btn btn-sm btn-pending">Pending</button>
<% elsif current_user.active_friends.include?(user) == true %>
    <%= link_to "Unfollow", friendship_path(current_user.friendships.find_by_friend_id(user.id)),
    :method => :delete, data: { confirm: "Are you sure?" }, class:"btn btn-sm btn-unfollow", remote: true %>
<% elsif current_user.follows?(user) == false %>
    <%= link_to "Follow", friendships_path(friend_id: user.id), method: :post, class: "btn btn-sm btn-follow", remote: true %>
<% end %>

app/views/users/_user.html.erb
<div class="row alternate-row" id="user_<%= user.id %>">
  <div class = "col-md-1 col-sm-2 col-xs-3 gravatar-user">
    <%= gravatar_for(user, size: 40) %>
  </div>
  <div class = "col-xs-2 small-gravatar-user">
    <%= gravatar_for(user, size: 30) %>
  </div>
  <div class = "col-md-9 col-sm-6 col-xs-4">
    <b><%= link_to user.name, user_path(user) %></b><br>
    <small><%= pluralize(user.articles.count, "article") if user.articles %></small>
  </div>
  <div class = "col-md-2 col-sm-4 col-xs-5 status_buttons">
    <%= render 'users/status_buttons', user: user %>
  </div>
</div>

app/views/users/followers.html.erb
<div class = "container">
  <div class = "row">
    <div class = "col-md-9 padding-top-20">

      <div id="tabs">   
        <ul class="nav nav-tabs">
          <li role="presentation" data-toggle="tab" ><a href="#tab1">Followers</a></li>
          <li role="presentation" class="active" data-toggle="tab"><a href="#tab2">Pending</a></li>
        </ul>
        <div class="tab-content">
          <div class="tab-pane followers" id="tab1">
            <%= render 'users/followers_list', followers: @followers %>
          </div>
          <div class="tab-pane active pending-requests" id="tab2">
            <%= render 'users/pending_list', requested_friendships: @requested_friendships %>
          </div>
        </div>
      </div> 
      
    </div>
    <div class = "col-md-3"></div>
  </div>
</div>

<script>
$(document).ready(function(){
    $(".nav-tabs a").click(function(){
        $(this).tab('show');
    });
});
</script>

app/views/users/following.html.erb
<div class = "container" id="following">
  <h3>You are following <%= pluralize(@following.count, 'person') %></h3>
  <% @following.each do |follow| %>
    <div class="row alternate-row" id ="following_<%= follow.id %>">
      <div class = "col-md-1 col-sm-2 col-xs-3">
        <%= gravatar_for(follow, size: 45) %>
      </div>
      <div class = "col-md-9 col-sm-6 col-xs-4">
        <b><%= link_to follow.name, user_path(follow) %></b><br>
      </div>
      <div class = "col-md-2 col-sm-4 col-xs-5 status_buttons">
        <%= link_to friendship_path(current_user.friendships.find_by_friend_id(follow.id)), :method => :delete,
          data: { confirm: "Are you sure?" }, class:"btn btn-unfollow", remote: true do %>
          <i class="fa fa-minus" aria-hidden="true"></i>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/users/index.html.erb
<div class = "container users-container">
  <%= search_form_for @search do |f| %>
    <div class = "row user-search-box">
      <div class="col-md-10 col-sm-10 col-xs-8">
         <%= f.search_field :name_cont, class: "form-control", id: "user_name_cont", name: "user[name_cont]", placeholder: "Search for a user" %>
      </div>
      <div class="col-md-2 col-sm-2 col-xs-4">
        <%= f.submit class: "btn btn-default" %>
      </div>
    </div>
  <% end %>
  <div id="users">
    <%= render @users %>
    <%= will_paginate @users, :inner_window => 1, :outer_window  => 1, :previous_label => '&larr;'.html_safe, :next_label => '&rarr;'.html_safe  %>
  </div>
</div>

app/views/users/index.js.erb
$('#users').html('<%= escape_javascript(render @users) %>')

app/views/users/show.html.erb
<div class = "container" id="user_<%= @user.id %>">   
  <% provide(:title, @user.name) %>
    <div class="row">
      <div class="col-md-4 col-xs-12 padding-top-20">
        <div class="well">
           <h1>
            <%= gravatar_for @user %>
            <%= @user.name %>
            <span style="padding-left: 20px", class= "status_buttons" %><%= render 'users/status_buttons_words', user: @user %></span>
           </h1>
           <h3><%= @user.received_friends.count %> followers</h3>
           <h3><%= @user.active_friends.count %> following</h3>
           <p><%= @user_articles.count %> articles</p>
        </div>
      </div>
      <div class="col-md-8 col-xs-12">
        <%= render partial: 'articles/article', collection: @user_articles %>
      </div>
    </div>
</div>