config/routes.rb
Rails.application.routes.draw do
  
  mount ActionCable.server => "/cable"
  
  resources :friendships, only: [:create, :update, :destroy]
  resources :categories, only: [:show, :index]
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :users, only: [:index, :show] do
    collection do   
      get 'search'
    end
  end

  get 'followers', to: 'users#followers'
  get 'following', to: 'users#following'
  get 'drafts', to: 'articles#drafts'
  
  resources :articles do
    resources :comments, only: [:create, :update, :destroy, :edit]
    member do
      get 'upvote'
      get 'downvote'
    end
  end
  
  resources :notifications, only: [:index, :destroy]
  
  resources :conversations, only: [:index, :new] do
    collection do   
      get 'list'
    end
  end

  resources :conversations, only: [:create] do
    resources :messages, only: [:create]
  end
  
  get 'refresh', to: 'pages#refresh'
  get 'follow_recommended', to: 'pages#follow_recommended'
  get 'about', to: 'pages#about'

  root 'pages#home'

  match "*path", to: "application#catch_404", via: :all

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
has_many :article_categories
has_many :articles, through: :article_categories
validates :name, presence: true
validates_uniqueness_of :name
is_impressionable :counter_cache => true, :unique => false

  def self.with_articles
    includes(:articles).where.not(articles: { id: nil, status: "draft" })
  end

  def self.order_by_impressions(current_user)
    self.joins(:articles)
        .joins(:impressions)
        .where(impressions: { user_id: current_user} )
        .group("categories.id")
        .order('categories.impressions_count DESC')
  end
  
  def self.top_3_visited(current_user)
    order_by_impressions(current_user).limit(3)
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
impressionist :actions=>[:show]

  def index
    if params[:id]
      @categories = Category.order('created_at DESC').where('id < ?', params[:id]).limit(3)
    else
      @categories = Category.order('created_at DESC').limit(3)
    end
    respond_to do |format|
      format.html
      format.js
    end
  end

  def show
    @category = Category.find(params[:id])
    @articles = @category.articles.order("impressions_count DESC").paginate(page: params[:page], per_page: 15)
    impressionist(@category)
  end

end

app/views/categories/_article.html.erb
<div class = "container-fluid">
  <div class="row">
    <div class="col-md-1 col-sm-1 col-xs-1"></div>
      <div class="col-md-10 col-xs-10">
        <div class="row">
          <% obj.each do |article| %>
            <div class="col-md-4 col-sm-12 col-xs-12" id="categorized_article_<%= article.id %>">
              <div class="panel panel-default">
                <div class="panel-heading">
                  <h4><%= link_to article.title, article_path(article) %></h4>
                </div>
                <div class="panel-body">
                  <p><%= article.summary %></p>
                  <small> <%= article.user.name if article.user%>, <%= time_ago_in_words(article.updated_at) %> ago</small>
                  <% if article.impressions_count == 1 %>
                    <span class="badge badge-pill badge-light"><%= article.impressions_count %> view</span>
                  <% else %>
                    <span class="badge badge-pill badge-light"><%= article.impressions_count %> views</span>
                  <% end %>
                </div>
               </div>
             </div>
          <% end %>
        </div>
      </div>
    <div class="col-md-1 col-sm-1 col-xs-1"></div>
  </div>
</div>

app/views/categories/_article_lg.html.erb
<div class = "container-fluid">
  <div class="row">
    <div class="col-md-1 col-sm-1 col-xs-1"></div>
      <div class="col-md-10 col-xs-10">
        <div class="row">
          <% obj.each do |article| %>
            <div class="col-md-6 col-sm-6 col-xs-6">
              <div class="panel panel-default">
                <div class="panel-heading">
                  <h4><%= link_to article.title, article_path(article) %></h4>
                </div>
                <div class="panel-body">
                  <p><%= article.summary %></p>
                  <small> <%= article.user.name if article.user%>, <%= time_ago_in_words(article.updated_at) %> ago</small>
                  <% if article.impressions_count == 1 %>
                    <span class="badge badge-pill badge-light"><%= article.impressions_count %> view</span>
                  <% else %>
                    <span class="badge badge-pill badge-light"><%= article.impressions_count %> views</span>
                  <% end %>
                </div>
               </div>
             </div>
          <% end %>
        </div>
      </div>
    <div class="col-md-1 col-sm-1 col-xs-1"></div>
  </div>
</div>

app/views/categories/_article_sm.html.erb
<div class = "container">
  <% obj.each do |article| %>  
    <div class = "row">
      <div id = "content-block" class="col-xs-12">
        <div id = "article-content">
          <h3><%= link_to article.title, article_path(article) %></h3>
          <p><%= article.summary %></p>
        </div>
        <div id = "category-block">
          <% article.categories.each do |category| %>
          <%= link_to "#{category.name}", category_path(category), class: "btn btn-xs btn-info" %>
          <% end %>
        </div>
      </div>
    </div>
   <hr>
  <% end %>
</div>

app/views/categories/_category.html.erb
<div class = "container-fluid">
    <% if category.articles.present? == true %>
      <div class="category" data-id="<%= category.id %>">
      
        <div class= "row cat-name-header">
          <%= link_to category_path(category), class: "btn btn-lg btn-cat-index" do %>
            <%= category.name %>
          <% end %>
        </div>
      
        <div class = "category-xlg">
          <%= render 'category_xlg', category: category %>
        </div>
        
        <div class = "category-lg">
          <%= render 'category_lg', category: category %>
        </div>
        
        <div class = "category-sm">
          <%= render 'category_sm', category: category %>
        </div>
      
      </div>
      
    <% end %>
</div>

app/views/categories/_category_lg.html.erb
<% div_id = "carousel_lg_#{category.id}" %>
  <div id="<%= div_id %>", class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
      <div class="item active">
        <div class="carousel-content">
          <%= render 'article_lg', obj: category.articles.order("impressions_count DESC").limit(2) %>
        </div>
      </div>
      <div class="item">
        <div class="carousel-content">
          <%= render 'article_lg', obj: category.articles.order("impressions_count DESC").limit(2).offset(3) %>
        </div>
      </div>
      <div class="item">
        <div class="carousel-content">
          <%= render 'article_lg', obj: category.articles.order("impressions_count DESC").limit(2).offset(5) %>
        </div>
      </div>
    </div>
    <% if category.articles.count > 3 %>
      <a class="left carousel-control" href="#<%= div_id %>" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left"></span>
      </a>
      <a class="right carousel-control" href="#<%= div_id %>" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right"></span>
      </a>
    <% end %>
  </div>
      

app/views/categories/_category_sm.html.erb
<%= render 'article_sm', obj: category.articles.order("impressions_count DESC").limit(3) %>

     

app/views/categories/_category_xlg.html.erb
<% div_id = "carousel_Xlg_#{category.id}" %>
  <div id="<%= div_id %>", class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
      <div class="item active">
        <div class="carousel-content">
          <%= render 'article', obj: category.articles.order("impressions_count DESC").limit(3) %>
        </div>
      </div>
      <div class="item">
        <div class="carousel-content">
          <%= render 'article', obj: category.articles.order("impressions_count DESC").limit(3).offset(3) %>
        </div>
      </div>
      <% if category.articles.count > 3 %>
        <a class="left carousel-control" href="#<%= div_id %>" role="button" data-slide="prev">
          <span class="glyphicon glyphicon-chevron-left"></span>
        </a>
        <a class="right carousel-control" href="#<%= div_id %>" role="button" data-slide="next">
          <span class="glyphicon glyphicon-chevron-right"></span>
        </a>
      <% end %>
    </div>
  </div>
      

app/views/categories/index.html.erb
<div style="background-color:#e0e3e4;">
  <img class='image' src="https://storage.googleapis.com/f1-project/website_images/categories.png"> 
</div>

<div id="category-container">
  <%= render @categories %>
</div>

<div class="load-more-container">
	<%= image_tag "ajax-loader.gif", style: "display:none;", class: "loading-gif" %>
	<%= link_to "Load More", categories_path, class: "btn btn-lg btn-cat-loadmore" %>
</div>


<script>
  $('.carousel').carousel({
    interval: false
}); 
</script>

app/views/categories/index.js.erb
$('#category-container').append('<%= escape_javascript(render @categories)%>');

app/views/categories/show.html.erb
<div class = "container">
  <div class= "load-more-container">
    <button class = "btn btn-lg btn-cat-loadmore" %>
      <%= @category.name %>
    </button>
  </div>
  
  <div class = "container">
    <%= render @articles %>
    <%= will_paginate @articles %>
  </div>
</div>